services:
  api_gateway:
    build: ./xbillpay-server
    ports:
      - "3000:3000"
    volumes:
      - ./xbillpay-server/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  agents_microservice:
    build: ./agents-microservice
    volumes:
      - ./agents-microservice/src:/usr/src/app/src
    command: npm run start:dev
  wallets_microservice:
    build: ./wallets-microservice
    volumes:
      - ./wallets-microservice/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - 4222:4222
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=helpapay
      - MYSQL_DATABASE=xbillpay_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
